services:
  foo_dev:
    image: ryftchen/foo:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: foo_dev
    environment:
      - FOO_ENV=foo_dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspaces/foo
    stdin_open: true
    tty: true
    privileged: true
    ulimits:
      core: -1
    command: /bin/bash
